INSERT INTO rr_users(user_id, first_name, last_name, email, password) VALUES(nextval('rr_users_seq'), 'Geddy', 'Lee', 'geddy@mail.com', '$2a$10$LF5Rf9lRXyZQ69FR7EF9Puqp.KomXyFeQyQAT6vEQ2mhJvy9MsU3G');
INSERT INTO rr_users(user_id, first_name, last_name, email, password) VALUES(nextval('rr_users_seq'), 'Jimmy', 'Page', 'jimmy@mail.com', '$2a$10$DcNMEVuyNGLVB5A7ZQrLve49b4eaZpo6abU3Gkpj87k34V/MzgED6');
INSERT INTO rr_users(user_id, first_name, last_name, email, password) VALUES(nextval('rr_users_seq'), 'John', 'Bonham', 'john@mail.com', '$2a$10$nBHcdD1OZfmQkZ7WlesWQOv4bQm1.6OQhp.hyHm3D.Fx2S/VVDXBO');

INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 1, 'Books about Wine', 'Books on wine from various regions of Europe and North America.');
INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 1, 'Baseball Books', 'My favorite books about baseball.');
INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 2, 'English & Misc. Architecture', 'Books on historical architecture of the British Isles.');
INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 2, 'Occult', 'Aleister Crowley and other freakshows that influenced Led Zeppelin.');
INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 2, 'Books About Led Zeppelin', 'A complete collection of books about my favorite band, Led Zeppelin.');
INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 3, 'Drinking, Farming, and Farm Equipment', 'All the books I own.');

INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 1, 1, 'OL9498223M', 'Sideways', '[{ "name": "Rex Pickett", "key": "OL1516108A" }]', 'TEMPCOVERURL', 'Kind of about wine.', 1704342375323);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 1, 1, 'OL49263761M', 'Vines in a Cold Climate', '[{ "name": "Henry Jeffreys", "key": "OL7614232A" }]', 'TEMPCOVERURL', null, 1704342378300);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 2, 1, 'OL26928111M', 'From the Dugouts to the Trenches', '[{ "name": "Jim Leeke", "key": "OL1075628A" }]', 'TEMPCOVERURL', null, 1704341378400);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 3, 2, 'OL7598311M', 'Philip Webb: Pioneer of Arts & Crafts Architecture', '[{ "name": "Sheila Kirk", "key": "OL2732304A" }]', 'TEMPCOVERURL', 'A great resource for info on the red house.', 1704341375550);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 3, 2, 'OL5472296M', 'The Cecils of Hatfield House', '[{ "name": "David Lord Cecil", "key": "OL1216967A" }]', 'TEMPCOVERURL', 'Book received from John Paul Jones.', 1704341377500);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 3, 2, 'OL8761224M', 'Bath', '[{ "name": "Thom Gorst", "key": "OL69317A" }]', 'TEMPCOVERURL', null, 1704341381405);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 4, 2, 'OL24580737M', 'Perdurabo: The Life of Aleister Crowley', '[{ "name": "Richard Kaczynski", "key": "OL3049062A" }]', 'TEMPCOVERURL', null, 1704341387905);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 4, 2, 'OL28643407M', 'The Kybalion: Centenary Edition', '[{ "name": "Three Initiates Staff", "key": "OL8103968A" }]', 'TEMPCOVERURL', null, 1704341387905);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 5, 2, 'OL27170707M', 'Jimmy Page by Jimmy Page', '[{ "name": "Jimmy Page", "key": "OL2872049A" }]', 'TEMPCOVERURL', 'The greatest book ever printed, by me.', 1704341388805);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 5, 2, 'OL34707062M', 'Led Zeppelin: The Biography', '[{ "name": "Bob Spitz", "key": "OL581376A" }]', 'TEMPCOVERURL', 'A wonderful story.', 1704341388966);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 5, 2, 'OL27594096M', 'Light and Shade: Conversations with Jimmy Page', '[{ "name": "Brad Tolinski", "key": "OL581376A" }]', 'TEMPCOVERURL', 'Wonderful conversations.', 1704341388777);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, ol_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 6, 3, 'OL34604027M', 'A Natural History Of The Hedgerow', '[{ "name": "John Wright", "key": "OL382542A" }]', 'TEMPCOVERURL', null, 1704341377951);