INSERT INTO rr_users(user_id, first_name, last_name, email, password) VALUES(nextval('rr_users_seq'), 'Geddy', 'Lee', 'geddy@mail.com', '$2a$10$LF5Rf9lRXyZQ69FR7EF9Puqp.KomXyFeQyQAT6vEQ2mhJvy9MsU3G');
INSERT INTO rr_users(user_id, first_name, last_name, email, password) VALUES(nextval('rr_users_seq'), 'Jimmy', 'Page', 'jimmy@mail.com', '$2a$10$DcNMEVuyNGLVB5A7ZQrLve49b4eaZpo6abU3Gkpj87k34V/MzgED6');
INSERT INTO rr_users(user_id, first_name, last_name, email, password) VALUES(nextval('rr_users_seq'), 'John', 'Bonham', 'john@mail.com', '$2a$10$nBHcdD1OZfmQkZ7WlesWQOv4bQm1.6OQhp.hyHm3D.Fx2S/VVDXBO');

INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 1, 'Books about Wine', 'Books on wine from various regions of Europe and North America.');
INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 1, 'Baseball Books', 'My favorite books about baseball.');
INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 2, 'English & Misc. Architecture', 'Books on historical architecture of the British Isles.');
INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 2, 'Occult', 'Aleister Crowley and other freakshows that influenced Led Zeppelin.');
INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 2, 'Books About Led Zeppelin', 'A complete collection of books about my favorite band, Led Zeppelin.');
INSERT INTO rr_shelves (shelf_id, user_id, title, description) VALUES(NEXTVAL('rr_shelves_seq'), 3, 'Drinking, Farming, and Farm Equipment', 'All the books I own.');

INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 1, 1, 'OL6032280W', 'Sideways', '[{ "name": "Rex Pickett", "libraryKey": "OL1516108A" }]', 'https://covers.openlibrary.org/b/id/180715-L.jpg', 'Kind of about wine.', 1704342375323);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 1, 1, 'OL35727480W', 'Vines in a Cold Climate', '[{ "name": "Henry Jeffreys", "libraryKey": "OL7614232A" }]', null, null, 1704342378300);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 2, 1, 'OL19714975W', 'From the Dugouts to the Trenches', '[{ "name": "Jim Leeke", "libraryKey": "OL1075628A" }]', 'https://covers.openlibrary.org/b/id/14359710-L.jpg', null, 1704341378400);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 3, 2, 'OL8208787W', 'Philip Webb: Pioneer of Arts & Crafts Architecture', '[{ "name": "Sheila Kirk", "libraryKey": "OL2732304A" }]', 'https://covers.openlibrary.org/b/id/300234-L.jpg', 'A great resource for info on the red house.', 1704341375550);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 3, 2, 'OL113116W', 'The Cecils of Hatfield House', '[{ "name": "David Lord Cecil", "libraryKey": "OL1216967A" }]', 'https://covers.openlibrary.org/b/id/4516303-L.jpg', 'Book received from John Paul Jones.', 1704341377500);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 3, 2, 'OL820369W', 'Bath', '[{ "name": "Thom Gorst", "libraryKey": "OL69317A" }]', 'https://covers.openlibrary.org/b/id/946298-L.jpg', null, 1704341381405);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 4, 2, 'OL15633392W', 'Perdurabo: The Life of Aleister Crowley', '[{ "name": "Richard Kaczynski", "libraryKey": "OL3049062A" }]', null, null, 1704341387905);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 4, 2, 'OL21158054W', 'The Kybalion: Centenary Edition', '[{ "name": "Three Initiates Staff", "libraryKey": "OL8103968A" }]', 'https://covers.openlibrary.org/b/id/13344966-L.jpg', null, 1704341387905);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 5, 2, 'OL19990593W', 'Jimmy Page by Jimmy Page', '[{ "name": "Jimmy Page", "libraryKey": "OL2872049A" }]', 'https://covers.openlibrary.org/b/id/13168614-L.jpg', 'The greatest book ever printed, by me.', 1704341388805);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 5, 2, 'OL8208787W', 'Philip Webb: Pioneer of Arts & Crafts Architecture', '[{ "name": "Sheila Kirk", "libraryKey": "OL2732304A" }]', 'https://covers.openlibrary.org/b/id/300234-L.jpg', 'I like this book so much I saved two copies.', 1704341375880);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 5, 2, 'OL25773811W', 'Led Zeppelin: The Biography', '[{ "name": "Bob Spitz", "libraryKey": "OL581376A" }]', null, 'A wonderful story.', 1704341388966);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 5, 2, 'OL16558410W', 'Light and Shade: Conversations with Jimmy Page', '[{ "name": "Brad Tolinski", "libraryKey": "OL581376A" }]', 'https://covers.openlibrary.org/b/id/9046376-L.jpg', 'Wonderful conversations.', 1704341388777);
INSERT INTO rr_saved_books (book_id, shelf_id, user_id, library_key, title, authors, cover_url, user_note, saved_date) VALUES(NEXTVAL('rr_saved_books_seq'), 6, 3, 'OL25732707W', 'A Natural History Of The Hedgerow', '[{ "name": "John Wright", "libraryKey": "OL382542A" }]', null, null, 1704341377951);